language: python
sudo: required

jdk:
  - oraclejdk7


addons:
  apt:
    packages:
    - python-setuptools
    - python-all
    - dh-make
    - protobuf-compiler
    - libprotobuf-java
    - python-protobuf
    - python-twisted
    - rpm
    
matrix:
  include:
    - os: linux
      dist: trusty
      python: "2.7_with_system_site_packages"

before_install:
 - export PATH=$PATH:$(pwd)/bin
 - pip install six -U
 - pip install pyOpenSSL ndg-httpsclient pyasn1  
 - jdk_switcher use openjdk7
 - jdk_switcher home openjdk7

install:
  - python setup.py sdist bdist_wheel
  - make rpm
  - make deb
  - VERSION=`git describe --tags  | cut -c 1-5`
  - sudo dpkg -i dist/drozer_$VERSION.deb
 
script:
  - ./bin/drozer

deploy:
  - provider: pypi
    user: "drozer"
    password:
      secure: gD9zqaooEJYDh8bOLivY0C/mVcIoeLVv9tdXmuLz7psZvuWrjGCGCrkB0K82iZGbfl8sbZyUsCN0bH2RcdrmRDqUkaRmXz6k+aiqraM4ZfVboVKDITTDYK6U0byfoBQ6AKJvqM0zcqXkZmg/5jWzx/IVUcfhEwK39u4NYGZWYGM=
    on:
      tags: true
      repo: mwrlabs/drozer
      branch: master
    distributions: "sdist bdist_wheel"

  - provider: releases
    api_key:
      secure: "fglL2kvuniMMXES6KxsDaODKXO9Detq0hnJHmX5/wYnvvyfJvIAWQHEDZBMCqh8SXX/ulhea6NWjKfVditxMUvVmEJRYrDmkBiA6ImvluatgVeDTJuXtVnnSbjE2CiD2IT/fAX+/PMdjyR8PVwdw7oxymcYUbqVrDFyYRPG+9WQ="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true

